In [2]:
#Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [4]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [8]:
#Yes, there is a difference in the data type of variables list_ and array_list.

#The variable list_ is a Python list, while the variable array_list is a numpy array.

#To print the data types of both the variables, you can use the type() function as follows:

import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [4]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [5]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
for element in list_:
    print("Data type of", element, "in list_:", type(element))

# Print data type of each element in array_list
for element in array_list:
    print("Data type of", element, "in array_list:", type(element))


Data type of 1 in list_: <class 'str'>
Data type of 2 in list_: <class 'str'>
Data type of 3 in list_: <class 'str'>
Data type of 4 in list_: <class 'str'>
Data type of 5 in list_: <class 'str'>
Data type of 1 in array_list: <class 'numpy.str_'>
Data type of 2 in array_list: <class 'numpy.str_'>
Data type of 3 in array_list: <class 'numpy.str_'>
Data type of 4 in array_list: <class 'numpy.str_'>
Data type of 5 in array_list: <class 'numpy.str_'>


In [11]:
#Q3. Considering the following changes in the variable, array_list:
#array_list = np.array(object = list_, dtype = int)
#Will there be any difference in the data type of the elements present in both the variables, list_ and
#array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [12]:
#Yes, there will be a difference in the data type of the elements present in both the variables list_ and array_list
#This code creates a numpy array from the list_ variable with the data type specified as int. This means that the elements of the numpy array will be integers, whereas the elements of the original list_ variable are strings.

import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for element in list_:
    print("Data type of", element, "in list_:", type(element))

# Print data type of each element in array_list
for element in array_list:
    print("Data type of", element, "in array_list:", type(element))


Data type of 1 in list_: <class 'str'>
Data type of 2 in list_: <class 'str'>
Data type of 3 in list_: <class 'str'>
Data type of 4 in list_: <class 'str'>
Data type of 5 in list_: <class 'str'>
Data type of 1 in array_list: <class 'numpy.int64'>
Data type of 2 in array_list: <class 'numpy.int64'>
Data type of 3 in array_list: <class 'numpy.int64'>
Data type of 4 in array_list: <class 'numpy.int64'>
Data type of 5 in array_list: <class 'numpy.int64'>


In [13]:
#Consider the below code to answer further questions:
#import numpy as np
#num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
#num_array = np.array(object = num_list)
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size

In [14]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of the num_array variable
print("Shape of num_array:", num_array.shape)

# Find the size of the num_array variable
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [16]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
#creation function.
#[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [19]:
import numpy as np

# Create a 3x3 numpy array containing only zeros
zeros_array = np.zeros(shape=(3, 3))

# Print the zeros_array variable
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
#[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [26]:
import numpy as np

#identity matrix of shape (5,5) using numpy functions
identity_matrix = np.eye(5)

# Print the identity_matrix variable
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
